apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook-config
webhooks:
  - name: admission-webhook.default.svc
    clientConfig:
      service:
        name: admission-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lVY0kwN3BoNnF1RDNiMVNJT0s0RnZ5QUlLN253d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0xERXFNQ2dHQTFVRUF3d2hZV1J0YVhOemFXOXVMWGRsWW1odmIyc3RjM1pqTG1SbFptRjFiSFF1YzNaagpNQjRYRFRJME1UQXhNREUzTXpZMU0xb1hEVEkxTVRBeE1ERTNNelkxTTFvd0xERXFNQ2dHQTFVRUF3d2hZV1J0CmFYTnphVzl1TFhkbFltaHZiMnN0YzNaakxtUmxabUYxYkhRdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUEyTHVrb1czaDlsRURSS1VKSXk1diszTE5oa3YwaldRU1dDeHdFVjBBZElNOQp0N3gva1Z3ZjA2cVlFZTlhM0swSWdUZTFLNVhuOEJ5WDRXNHE0cWoyVk5CTE41cDFVcm43TzdhSURwOXFuaXEvClk1Ulk3aVNaVk4xVGhFVG93Wi9uR0lGV0JNUmhSc2I0RkFxUVdaR3ZEclF5bFVIN2hreC9ScytoeThOVlBUYUwKOFhDLzJwYXVRcDI5dGxrb2xoRzN0eEhqNk5QazZIK3psUHBka1VjNXg2S3ZpckxkSmRyT2hxTzZDamhlQ1ZGSQpWemhOOGE4emRFOTQ0Mi9oc1AwZVhEMTJVMUR1ZnVUc3dMVFVGWnppQXdpNGoyUHFlb1NMQzQyV3hWaHFsanJOCitaK01VUnd3Z01RaEhBNzJIL2ZIOUJpcThFZXQvMDBoaUZVSlBwbHo2d0lEQVFBQm80R0dNSUdETUdJR0ExVWQKRVFSYk1GbUNGV0ZrYldsemMybHZiaTEzWldKb2IyOXJMWE4yWTRJZFlXUnRhWE56YVc5dUxYZGxZbWh2YjJzdApjM1pqTG1SbFptRjFiSFNDSVdGa2JXbHpjMmx2YmkxM1pXSm9iMjlyTFhOMll5NWtaV1poZFd4MExuTjJZekFkCkJnTlZIUTRFRmdRVU85em5FKy9MODFKV2JXempLT2dKSjFSN3FsQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQURwNGdxSWh6aFZtcDJlQU50ZitUZ3N2bDFITUZJc1hqbGtlZFZnQ0ZKdU5PR01MM1BuWTAvN1BjOWlxVW9sSgpqYStiVkxNcU9QOXNnYkhWUmZrOWEvQ1lWb0NyRGVUTThWSng4Mi9uNlludjBmTmk2UzBDRUFLS3ZwZ0hWQTdvCjRrUnRnbENlUlA5bG43dnI2SkRnaXlRQ3FrL0VCTFFEV1A3bnBvaVMrMGphU2k3MXhiQTN5UnpsWHI2N0ZNTmQKOVZiZk9iUC9ra0Z6Z0NRb2Y5bEhtTnEvckViTCtZUEtFWlFXNldqL0t5ZFFSMnNJZEdqMEdubUpWRW5EOVVycQo2MG4wSnF5Yk9JT0tUUE9JVWxJOHRNbytEYUNSMGkwZTJJWi9zVFlBbG12dWFTUkpGWlNiUXZlaDEwd1pLd1RXCmlHaW1HaWlUbUFDUGVOQVB0elpMUU5JPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    sideEffects: None

